pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('client') {
                    echo 'Building the project...'
                    sh 'npm install -g yarn'
                    sh 'yarn build'
                }
            }
        }
    }
}
