version: '3'

services:
  react:
    image: dajeongyun/docker-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /client:/app
    ports:
      - '3000:3000'
    stdin_open: true

  springboot:
    image: dajeongyun/docker-springboot-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'

  redis-server:
    image: redis

  nodejs:
    image: dajeongyun/docker-nodejs-server
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    depends_on:
      - redis-server
    volumes:
      - /app/node_modules
      - ./socket-server:/app
    ports:
      - '8005:8005'
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
# volumes:
#   redis-data:
