version: '3'

services:
  client:
    container_name: bidking_client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /client:/app
    stdin_open: true

  nginx:
    container_name: bidking_nginx
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  server:
    container_name: bidking_server
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"

  db:
    container_name: bidking_database
    build: ./mysql
    restart: unless-stopped
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    container_name: bidking_redis
    image: redis:7.0.5
    ports:
      - "16379:6379"
  