version: '3'

services:
  client:
    image: dajeongyun/docker-client
    container_name: bidking_client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /client:/app
    stdin_open: true

  server:
    image: dajeongyun/docker-springboot-server
    container_name: bidking_server
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"

  live:
    image: dajeongyun/docker-socket-server
    container_name: bidking_live
    volumes:
      - /app/node_modules
      - ./live:/app
    mem_limit: 128m

  redis:
    container_name: bidking_redis
    image: redis:7.0.5
    ports:
      - "16379:16379"
  