version: '3'

services:
  redis-server:
    image: redis
    # command: ['redis-server', '--bind', 'redis', '--port', '6379']
    container_name: redis
    ports:
      - '6379:6379'

  react:
    image: dajeongyun/docker-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    stdin_open: true

  springboot:
    image: dajeongyun/docker-springboot-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'

  nodejs:
    image: dajeongyun/docker-nodejs-server
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    volumes:
      - /app/node_modules
      - ./socket-server:/app
    depends_on:
      - 'redis-server'
# volumes:
#   redis-data:
