version: "3"

services:
  react:
    image: dajeongyun/docker-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /client:/app/build
    ports:
      - "3000:3000"
    stdin_open: true

  springboot:
    image: dajeongyun/docker-springboot-server
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"

  redis-server:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "16379:6379"
      
  
  nodejs:
    image: dajeongyun/docker-nodejs-server
    build: 
      context: ./socket-server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./socket-server:/app
    mem_limit: 128m
    ports:
      - "8005:8005"

volumes:
  redis-data: