version: "3"

services:
  react:
    image: dajeongyun/docker-client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /client:/app/build
    ports:
      - 3000:3000
    stdin_open: true

  springboot:
    image: dajeongyun/docker-springboot-server
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000

  nodejs:
    image: dajeongyun/docker-nodejs-server
    build: 
      dockerfile: Dockerfile
      context: ./socket-server
    volumes:
      - /app/node_modules
      - ./socket-server:/app
    mem_limit: 128m
    ports:
      - 8005:8005

  redis:
    image: redis
    ports:
      - 16379:16379
  