pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                ls
                cd server
                ls
                echo 'Hello World'
            }
        }
    }
}