pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'springboot server build start...'
                sh './gradlew clean build'
            }
        }
    }
}
